services:
  pytorch-nvcc-service:
    #container_name: cuda-nvcc-container
    #image: nvcr.io/nvidia/pytorch:23.07-py3
    build: .
    ipc: host
    ports:
      - 8888:8888   
    volumes:
      - ../data:/home/data

    #stdin_open: true 
    #tty: true

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    
    command: sleep infinity
    #command: jupyter-lab --notebook-dir=/home/cuda/data --ip=0.0.0.0 --no-browser --NotebookApp.token='' --NotebookApp.allow_origin='*' --NotebookApp.base_url=\"${NB_PREFIX:-/}\"